apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: node:18

        command: ["sh", "-c"]

        args:
          - |
            echo "const http = require('http');
            const server = http.createServer((req,res)=>{
            res.end('Backend API Working');
            });
            server.listen(3000);" > app.js && node app.js

        ports:
        - containerPort: 3000